"""Configuration package for Twitch Drops Miner."""

from __future__ import annotations

# Re-export all public symbols for convenience
from .constants import (
    CALL,
    FILE_FORMATTER,
    OUTPUT_FORMATTER,
    LOGGING_LEVELS,
    State,
    WebsocketTopic,
    WEBSOCKET_TOPICS,
    JsonType,
    URLType,
    TopicProcess,
    GQLOperation,
    MAX_INT,
    MAX_EXTRA_MINUTES,
    BASE_TOPICS,
    MAX_WEBSOCKETS,
    WS_TOPICS_LIMIT,
    TOPICS_PER_CHANNEL,
    MAX_TOPICS,
    MAX_CHANNELS,
    DEFAULT_LANG,
    PING_INTERVAL,
    PING_TIMEOUT,
    ONLINE_DELAY,
    WATCH_INTERVAL,
    WINDOW_TITLE,
)
from .paths import (
    IS_APPIMAGE,
    IS_PACKAGED,
    IS_DOCKER,
    SYS_SITE_PACKAGES,
    SYS_SCRIPTS,
    SELF_PATH,
    WORKING_DIR,
    DATA_DIR,
    VENV_PATH,
    SITE_PACKAGES_PATH,
    SCRIPTS_PATH,
    LANG_PATH,
    LOG_PATH,
    DUMP_PATH,
    LOCK_PATH,
    CACHE_PATH,
    CACHE_DB,
    COOKIES_PATH,
    SETTINGS_PATH,
    _resource_path,
    _merge_vars,
)
from .client_info import ClientInfo, ClientType
from .operations import GQL_OPERATIONS

__all__ = [
    # constants.py
    "CALL",
    "FILE_FORMATTER",
    "OUTPUT_FORMATTER",
    "LOGGING_LEVELS",
    "State",
    "WebsocketTopic",
    "WEBSOCKET_TOPICS",
    "JsonType",
    "URLType",
    "TopicProcess",
    "GQLOperation",
    "MAX_INT",
    "MAX_EXTRA_MINUTES",
    "BASE_TOPICS",
    "MAX_WEBSOCKETS",
    "WS_TOPICS_LIMIT",
    "TOPICS_PER_CHANNEL",
    "MAX_TOPICS",
    "MAX_CHANNELS",
    "DEFAULT_LANG",
    "PING_INTERVAL",
    "PING_TIMEOUT",
    "ONLINE_DELAY",
    "WATCH_INTERVAL",
    "WINDOW_TITLE",
    # paths.py
    "IS_APPIMAGE",
    "IS_PACKAGED",
    "IS_DOCKER",
    "SYS_SITE_PACKAGES",
    "SYS_SCRIPTS",
    "SELF_PATH",
    "WORKING_DIR",
    "DATA_DIR",
    "VENV_PATH",
    "SITE_PACKAGES_PATH",
    "SCRIPTS_PATH",
    "LANG_PATH",
    "LOG_PATH",
    "DUMP_PATH",
    "LOCK_PATH",
    "CACHE_PATH",
    "CACHE_DB",
    "COOKIES_PATH",
    "SETTINGS_PATH",
    "_resource_path",
    "_merge_vars",
    # client_info.py
    "ClientInfo",
    "ClientType",
    # operations.py
    "GQL_OPERATIONS",
]
